# -*- coding: utf-8 -*-
"""PRACTICA_AST_Clase_5_2A(RandyCat).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15nuEnSBF2QuVwdkX8irnFil2IIU3KXzO

<div class="alert alert-block alert-info">
    <h1>Análisis de Series Temporales</h1>
    <h3>Clase 5 - Modelos de Ensambles - CatBoost y RandomForest </h3>
    <h3>Ejercicio 2A_Sincronico</h3>
        <p>Docentes: Rodrigo Del Rosso, Drago Braian, Sebastian Calcagno <p>
</div>

**Modelos Ensambles**  

La idea principal detras de los modelos de ensamble es entrenar una serie de WEAK LEARNERS para que juntos formen un STRONG LEARNER.  
Lo que le da poder a estos modelos es que se compensan los errores base de unos modelos con otros, dandole mayor robustez y menor tendencia al overfitting.  


Bagging (Bootstrap Aggregating) es una técnica de ensamble que implica entrenar múltiples modelos independientes en diferentes subconjuntos de los datos, que se obtienen mediante muestreo con reemplazo (bootstrap). **Aqui los modelos se entrenan de manera independiente pero en paralelo**. Los resultados de estos modelos se combinan para mejorar la precisión y reducir la varianza. El más comúnmente conocido es **Random Forest**.  

Random Forest combina un set de arboles de decisión para hacer predicciones.

¿Qué es el Boosting? Boosting es una técnica conjunta de aprendizaje automático que combina múltiples modelos débiles (weak models) en un único modelo fuerte. En Boosting, cada modelo aprende de los errores del modelo anterior, lo que da como resultado un modelo mejor en general. El objetivo es mejorar la precisión de un modelo reduciendo la varianza y el sesgo en los datos.  

**Boosting** suele mejorar el poder de predicción ya que **entrena weak learners de manera secuencial**, donde cada vez compensa los errores del anterior.(Enfoque en ajustar los errores anteriores).  

**CatBoost** utiliza un enfoque de ordenado por niveles (level-wise growth) para construir los árboles, similar a XGBoost. Este método tiende a construir árboles más equilibrados.  
CatBoost se especializa en manejar variables categóricas de manera nativa sin necesidad de preprocesamiento.    
Tiene menos hiperparámetros que ajustar, lo que simplifica la experimentación y optimización.  

1996: AdaBoost - Adaptive Boosting (Primer algoritmo Boosting).  
1999: Gradient Boosting Machine (GBM) (Introducción del enfoque de gradientes).  
*2001:* Random Forest (Introducción del algoritmo basado en Bagging).  
*2014:* XGBoost (Optimización y popularización del Boosting).  
*2016:* LightGBM (Mayor velocidad y escalabilidad, mejor para datasets grandes).  
*2017:* CatBoost (Manejo eficiente de variables categóricas).  


https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html  
https://catboost.ai/en/docs/

**Objetivo del Ejercicio**:  
Nos centraremos en el problema del consumo de energía, donde, dado un conjunto de datos suficientemente grande del consumo diario de energía de diferentes hogares en una ciudad, tenemos la tarea de predecir con la mayor precisión posible las demandas energéticas futuras.  

El dataset contiene el consumo de energía de 5.567 hogares seleccionados al azar en la ciudad de Londres durante el período comprendido entre noviembre de 2011 y febrero de 2014.  

Nota: Como queremos predecir el consumo de forma general y no por hogar, debemos agrupar los resultados por fecha y promediar los kilovatios-hora.

FUENTE DEL DATASET: https://www.kaggle.com/datasets/emmanuelfwerr/london-homes-energy-data

Carga de Librerías
"""

pip install catboost

import pandas as pd
import requests
from io import BytesIO
import zipfile
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#import xgboost as xgb
import catboost
from catboost import CatBoostRegressor
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import TimeSeriesSplit
#from xgboost import plot_importance, plot_tree
color_pal = sns.color_palette()
plt.style.use('tableau-colorblind10')

# URL del archivo ZIP en GitHub
zip_url = 'https://github.com/braiandrago/AST/blob/main/london_energy.csv.zip?raw=true'

# Descargar el archivo ZIP
response = requests.get(zip_url)
if response.status_code == 200:
    # Leer el contenido del archivo ZIP en un objeto BytesIO
    zip_content = BytesIO(response.content)

    # Descomprimir el archivo ZIP y extraer el archivo CSV
    with zipfile.ZipFile(zip_content, 'r') as zip_file:
        # Asignar nombre del archivo csv
        csv_file_name = 'london_energy.csv'
        with zip_file.open(csv_file_name) as csv_file:
            # Leer el archivo CSV en un DataFrame
            df = pd.read_csv(csv_file)

    # Mostrar la información del DataFrame
    df.info()
else:
    print("Error al descargar el archivo ZIP")

"""`LCLid` es una cadena única que identifica a cada hogar.   
`Date` variable tiempo.  
`KWH` es el número total de kilovatios-hora gastados en esa fecha y no falta ningún valor.

# Carga y Procesamiento inicial del dataset
"""

df.head()

print(df.isna().sum())

"""Agrupamos los datos por la columna "Date" y calculamos el promedio de la columna "KWH" para cada grupo (es decir, el consumo promedio por día) y convertimos el resultado a un dataframe"""

df_avg_consumption = df.groupby("Date")["KWH"].mean()
df_avg_consumption = pd.DataFrame({"date": df_avg_consumption.index.tolist(), "consumption": df_avg_consumption.values.tolist()})
df_avg_consumption["date"] = pd.to_datetime(df_avg_consumption["date"])
print(f"From: {df_avg_consumption['date'].min()}")
print(f"To: {df_avg_consumption['date'].max()}")

df_avg_consumption.head()

df_avg_consumption.tail()

df_avg_consumption.plot(x="date", y="consumption");

"""Estacionalidad:"""

df_avg_consumption.query("date > '2012-01-01' & date < '2013-01-01'").plot(x="date", y="consumption");

"""**Feature Enginering**

De manera similar a los ejercicios anteriores....Para entrenar un modelo como XGBoost y LightGB necesitamos crear las funciones nosotros mismos. Actualmente, solo tenemos una característica: la fecha completa. Podemos extraer diferentes características en función de la fecha completa como el día de la semana, el día del año, el mes y otros.
"""

df_avg_consumption["day_of_week"] = df_avg_consumption["date"].dt.dayofweek
df_avg_consumption["day_of_year"] = df_avg_consumption["date"].dt.dayofyear
df_avg_consumption["month"] = df_avg_consumption["date"].dt.month
df_avg_consumption["quarter"] = df_avg_consumption["date"].dt.quarter
df_avg_consumption["year"] = df_avg_consumption["date"].dt.year

df_avg_consumption.head()

"""**Separación de los datos para el modelado:**

Hasta aqui... date no fue tratada como index. Podemos utilizarla para separar los datos y luego eliminarla.

Para el conjunto de pruebas usaremos solo los últimos 6 meses. Si el conjunto de entrenamiento fuera más grande, habríamos utilizado todo el último año como conjunto de pruebas.
"""

training_mask = df_avg_consumption["date"] < "2013-07-28"
training_data = df_avg_consumption.loc[training_mask]
print(training_data.shape)

testing_mask = df_avg_consumption["date"] >= "2013-07-28"
testing_data = df_avg_consumption.loc[testing_mask]
print(testing_data.shape)

figure, ax = plt.subplots(figsize=(20, 5))
training_data.plot(ax=ax, label="Training", x="date", y="consumption")
testing_data.plot(ax=ax, label="Testing", x="date", y="consumption")
plt.show()

# Dropping unnecessary `date` column
training_data = training_data.drop(columns=["date"])
testing_dates = testing_data["date"]
testing_data = testing_data.drop(columns=["date"])

X_train = training_data[["day_of_week", "day_of_year", "month", "quarter", "year"]]
y_train = training_data["consumption"]

X_test = testing_data[["day_of_week", "day_of_year", "month", "quarter", "year"]]
y_test = testing_data["consumption"]

"""**Entrenamiento del modelo:**

La optimización de los hiperparámetros se realizará con gridsearch, la cual toma parámetros y algunos valores como configuración y prueba todas las combinaciones posibles.

Nuevamente, debido a la naturaleza del problema, no podemos simplemente usar una validación cruzada simple de k veces. Scikit learn proporciona el método TimeSeriesSplit que divide los datos de forma incremental de manera respetuosa en términos de continuidad.

**Para Catboost:**
"""

from sklearn.model_selection import TimeSeriesSplit, GridSearchCV

# CatBoost
cv_split = TimeSeriesSplit(n_splits=4, test_size=100)
model = CatBoostRegressor()
model = CatBoostRegressor(learning_rate=0.1, n_estimators=100, depth=7)

parameters = {
    "depth": [3, 4, 5, 6, 7],
    "learning_rate": [0.01, 0.05, 0.1, 0.2, 0.3],
    "n_estimators": [100, 300, 500, 700, 900, 1000],
    "colsample_bylevel": [0.3, 0.5, 0.7]
}

grid_search = GridSearchCV(estimator=model, cv=cv_split, param_grid=parameters)
grid_search.fit(X_train, y_train)

"""**Evaluación**"""

from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error,\
  mean_squared_error

def evaluate_model(y_test, prediction):
  print(f"MAE: {mean_absolute_error(y_test, prediction)}")
  print(f"MSE: {mean_squared_error(y_test, prediction)}")
  print(f"MAPE: {mean_absolute_percentage_error(y_test, prediction)}")

def plot_predictions(testing_dates, y_test, prediction):
  df_test = pd.DataFrame({"date": testing_dates, "actual": y_test, "prediction": prediction })
  figure, ax = plt.subplots(figsize=(10, 5))
  df_test.plot(ax=ax, label="Actual", x="date", y="actual")
  df_test.plot(ax=ax, label="Prediction", x="date", y="prediction")
  plt.legend(["Actual", "Prediction_CatBoost"])
  plt.show()

# Evaluating GridSearch results
prediction = grid_search.predict(X_test)
plot_predictions(testing_dates, y_test, prediction)
evaluate_model(y_test, prediction)

"""**Random Forest**

Random Forest es un modelo de ensamble basado en árboles de decisión, y su funcionamiento no depende de un proceso iterativo de optimización como en los modelos de Gradient Boosting o redes neuronales
"""

# RandomForest
from sklearn.ensemble import RandomForestRegressor
cv_split = TimeSeriesSplit(n_splits=4, test_size=100)
model = RandomForestRegressor()
parameters = {
    "max_depth": [3, 4, 6, 5, 10],
    "n_estimators": [50, 100, 300, 500, 700, 900, 1000],
    "min_samples_split":[2, 4, 6, 10],
    "max_leaf_nodes": [2, 4, 8]
}


grid_search = GridSearchCV(estimator=model, cv=cv_split, param_grid=parameters)
grid_search.fit(X_train, y_train)

def plot_predictions(testing_dates, y_test, prediction):
  df_test = pd.DataFrame({"date": testing_dates, "actual": y_test, "prediction": prediction })
  figure, ax = plt.subplots(figsize=(10, 5))
  df_test.plot(ax=ax, label="Actual", x="date", y="actual")
  df_test.plot(ax=ax, label="Prediction", x="date", y="prediction")
  plt.legend(["Actual", "Prediction_RandomForest"])
  plt.show()

# Evaluating GridSearch results
prediction = grid_search.predict(X_test)
plot_predictions(testing_dates, y_test, prediction)
evaluate_model(y_test, prediction)